### ISSUE TITLE
Rename PressureDataFrame into BloodPressureDataFrame

### ISSUE THREAD

**Issue by Makman2** [Makman2/MP#5]
In my opinion `PressureDataFrame` is a way too generic name. Since our application measures explicitly **blood** pressure we should call the object more appropriate (`BloodPressureDataFrame`).

**Comment by ploader** [comment]
i like that...

**Comment by ploader** [comment]
And since we´re not develop a game i think  a intro video is not necessary?!
It shood pop up directly to our wifi scanner....and from there to our main window.

**Comment by Makman2** [comment]
a video would be an overkill :D
The app should be self-explainable^^
